language: php
php:
    - '5.6'
services: mysql
install:
    - composer install
    - cp .env.example .env
    - sed -i 's/^DB_USERNAME=.*$/DB_USERNAME=root/g' .env
    - sed -i 's/^DB_PASSWORD=.*$/DB_PASSWORD=/g' .env
    - sed -i 's/^DB_DATABASE=.*$/DB_DATABASE=testing_db/g' .env
    - mysqladmin create testing_db
    - php artisan key:generate
    - php artisan migrate
    - php artisan migrate:rollback
    - php artisan migrate
script: composer ci
